# Generated by Django 4.0.5 on 2022-07-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=30)),
                ('num_local', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=30)),
                ('precio', models.PositiveIntegerField()),
                ('marca', models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple')], default='Samsung', max_length=20)),
                ('stock', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('local', models.CharField(choices=[('Local 1', 'Local 1'), ('Local 2', 'Local 2')], default='Local 1', max_length=10)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
