# Generated by Django 4.0.5 on 2022-07-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locales',
            options={'verbose_name_plural': 'Locales'},
        ),
        migrations.AlterField(
            model_name='locales',
            name='num_local',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='marca',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Select'), (1, 'Apple'), (2, 'Samsung')], verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='vendedores',
            name='local',
            field=models.CharField(max_length=30),
        ),
    ]
