# Generated by Django 4.0.5 on 2022-07-02 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_locales_options_alter_locales_num_local_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='vendedores',
            options={'verbose_name_plural': 'Vendedores'},
        ),
        migrations.RenameField(
            model_name='locales',
            old_name='direccion',
            new_name='address',
        ),
    ]
