# Generated by Django 4.0.5 on 2022-07-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_productos_options_alter_vendedores_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locales',
            old_name='num_local',
            new_name='mall_number',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='marca',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='precio',
            new_name='prize',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='producto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='vendedores',
            old_name='fecha_nacimiento',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='vendedores',
            old_name='apellido',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='vendedores',
            old_name='local',
            new_name='mall_number',
        ),
        migrations.RenameField(
            model_name='vendedores',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AddField(
            model_name='locales',
            name='city',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Córdoba'), (2, 'Capital Federal'), (3, 'Rosario'), (4, 'Mendoza'), (5, 'Salta')], default=1, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='locales',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='locales',
            name='opening_hours',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday to friday'), (2, 'Monday to saturday'), (3, 'Monday to monday')], default=1, verbose_name='Opening days'),
        ),
        migrations.AlterField(
            model_name='locales',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
