# Generated by Django 4.0.5 on 2022-07-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_productos_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nuevos_Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('release_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Nuevos Productos',
            },
        ),
    ]
